[package]
name = "tcpclient"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.163", features = ["derive"]}
serde_json = "1.0.96"
crypto= {path = "../crypto"}
http= {path="../http"}
bincode = "1.3"
rand = "0.8"
rsa = { version = "0.9.6", features = ["std", "serde"] }